language: generic

services: docker

cache:
  directories:
  - $HOME/emacs-src

env:
  - GIT_BRANCH="emacs-23.4"       DOCKER_TAGS="23.4 23"
  - GIT_BRANCH="emacs-24.5"       DOCKER_TAGS="24.5 24"
  - GIT_BRANCH="emacs-25.1"       DOCKER_TAGS="25.1"
  - GIT_BRANCH="emacs-25.2"       DOCKER_TAGS="25.2"
  - GIT_BRANCH="emacs-25.3"       DOCKER_TAGS="25.3 25 latest"
  - GIT_BRANCH="emacs-26.0.91"    DOCKER_TAGS="26.0"
  - GIT_BRANCH="master"           DOCKER_TAGS="master"

before_install: source functions.sh

before_script: fetch

script: build

after_success: push

notifications:
  email:
    on_success: never
    on_failure: never
