language: generic

services: docker

cache:
  timeout: 900
  directories:
  - $HOME/cache

env:
{{ENV}}

before_install:
  - source bin/setup-env

before_script:
  - image-prepare "$GIT_REPOSITORY" "$GIT_BRANCH" "$TRAVIS_CACHE/emacs/$GIT_BRANCH" "$IMAGE_DIRECTORY"
  - docker-load-images "$TRAVIS_CACHE/docker/images.tar"

script:
  - image-build "$DOCKER_REPOSITORY" "$IMAGE_TAGS" "$IMAGE_DIRECTORY"

after_success:
  - image-push "$DOCKER_REPOSITORY" "$IMAGE_TAGS"
  - docker-save-images "$TRAVIS_CACHE/docker/images.tar"

notifications:
  email:
    on_success: never
    on_failure: never
